# https://gohugo.io/getting-started/configuration
baseURL: https://will4j.github.io
title: Programmer William Wang
theme: FixIt

# Default number of elements per page in pagination.
# https://gohugo.io/templates/pagination/
paginate: 5

# https://gohugo.io/hugo-modules/use-modules/
# https://gohugo.io/hugo-modules/configuration/
module:
  imports: [ ]

# https://gohugo.io/content-management/related/#configure-related-content
related:
  includeNewer: true
  threshold: 60
  toLower: false
  indices:
    - name: tags
      weight: 100
    - name: categories
      weight: 200

# Content without language indicator will default to this language.
defaultContentLanguage: zh-cn
languageCode: en
defaultContentLanguageInSubdir: false
# see languages.yaml

# https://gohugo.io/getting-started/configuration-markup/
markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: true
  highlight:
    noClasses: false
    codeFences: true
    guessSyntax: true
    lineNoStart: 1
    lineNos: true
    lineNumbersInTable: true
    tabWidth: 4
  tableOfContents:
    endLevel: 4
    ordered: true
    startLevel: 2

# Enable Emoji emoticons support for page content;
# https://gohugo.io/quick-reference/emojis/
enableEmoji: true
# Enable .GitInfo object for each page (if the Hugo site is versioned by Git).
# This will then update the Lastmod parameter for each page using the last git commit date for that content file.
enableGitInfo: true
# The length of text in words to show in a .Summary.
summaryLength: 150
# https://gohugo.io/getting-started/configuration/#configure-front-matter
frontmatter:
  lastmod: [ "lastmod", ":git", ":fileModTime", ":defalut" ]

# Include drafts when building.
buildDrafts: false

# Enable generation of robots.txt file.
enableRobotsTXT: true
# Copyright notice for your site, typically displayed in the footer.
copyright: by 水王
