# https://gohugo.io/content-management/multilingual/#configure-languages
zh-cn:
  # 这里大小写很重要，定义网站html lang
  languageCode: zh-CN
  languageName: 简体中文
  # If true, auto-detect Chinese/Japanese/Korean Languages in the content.
  # This will make .Summary and .WordCount behave correctly for CJK languages.
  hasCJKLanguage: true

  title: 程序员水王
  params:
    description: 程序员水王的个人博客
    home:
      profile:
        subtitle: 行百里者半九十。
    header:
      title:
        name: 程序员水王
    app:
      title: 程序员水王
