# https://gohugo.io/content-management/menus
# https://gohugo.io/content-management/multilingual/#menus
main: [ ]
social:
  - identifier: github
    name: GitHub
    url: https://github.com/will4j
    params:
      icon: brand-github
