# https://fixit.lruihao.cn/documentation/basics/#theme-configuration

header:
  title:
    logo: ""
    name: William Wang's Note
    pre: <i class="fa fa-code"></i>
    typeit: true

defaultTheme: auto
dateFormat: "2006-01-02"

home:
  profile:
    enable: true
    subtitle: The last leg of a journey just marks the halfway point.
    avatarMenu: github
    avatarURL: /img/avatar.png
  posts:
    enable: true
    paginate: 6

social:
  GitHub: will4j
  Email: williamw0825@gmail.com

search:
  enable: true
  type: fuse
  fuse:
    # https://fusejs.io/api/options.html
    isCaseSensitive: false

page:
  comment:
    enable: true
    giscus:
      enable: true
      repo: will4j/will4j.github.io
      repoId: R_kgDOKuAcSg
      category: Announcements
      categoryId: DIC_kwDOKuAcSs4CbAb9
      mapping: pathname
      strict: "0"
      reactionsEnabled: "1"
      emitMetadata: "0"
      inputPosition: bottom
      lang: zh-CN

footer:
  enable: true
  since: 2023
  hugo: true
  siteTime:
    enable: true
    value: "2023-11-16T07:40:29+08:00"
  license: '<a rel="license external nofollow noopener noreferrer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'
  order:
    powered: 1
    copyright: last
    statistics: first

section:
  recentlyUpdated:
    enable: true

tagCloud:
  enable: true

breadcrumb:
  enable: true

app:
  svgFavicon: /favicon.svg

description: William Wang's Note.
keywords: ["Programming", "Software Engineering", "DevOps", "Kubernetes"]
