# https://stack.jimmycai.com/config/site
mainSections:
  - posts
# Output page's full content in RSS.
rssFullContent: true
favicon: /favicon.ico

# https://stack.jimmycai.com/config/article
article:
  math: true
  toc: true
  readingTime: true

# https://stack.jimmycai.com/config/sidebar
sidebar:
  emoji: 🍥
  subtitle: The last leg of a journey just marks the halfway point.
  avatar:
    enabled: true
    local: true
    src: img/avatar.png

# https://stack.jimmycai.com/config/widgets
widgets:
  homepage:
    - type: search
    - type: archives
      params:
        limit: 5
    - type: categories
      params:
        limit: 10
    - type: tag-cloud
      params:
        limit: 10
  page:
    - type: toc

# https://stack.jimmycai.com/config/color-scheme
colorScheme:
  # Display toggle
  toggle: true
  # Available values: auto, light, dark
  default: auto

# https://stack.jimmycai.com/config/date-format
dateFormat:
  published: Jan 02, 2006
  lastUpdated: Jan 02, 2006 15:04 MST

# https://stack.jimmycai.com/config/footer
footer:
  since: 2023
