# https://fixit.lruihao.cn/documentation/basics/#theme-configuration

header:
  title:
    logo: ""
    name: Programmer William Wang
    pre: <i class="fa fa-code">&nbsp</i>
    typeit: true

defaultTheme: auto
dateFormat: "2006-01-02"

home:
  profile:
    enable: true
    subtitle: The last leg of a journey just marks the halfway point.
    avatarMenu: github
    avatarURL: /img/avatar.png
  posts:
    enable: true
    paginate: 6

social:
  GitHub: will4j
  Email: williamw0825@gmail.com
  RSS: true

# https://fixit.lruihao.cn/documentation/basics/#search-configuration
search:
  enable: true
  type: fuse
  fuse:
    # https://fusejs.io/api/options.html
    isCaseSensitive: false

page:
  comment:
    enable: true
    giscus:
      enable: true
      repo: will4j/blog-resource
      repoId: R_kgDOKus4vg
      category: Blog Comments
      categoryId: DIC_kwDOKus4vs4CbCP2
      mapping: pathname
      strict: "0"
      reactionsEnabled: "1"
      emitMetadata: "0"
      inputPosition: bottom
      lang: zh-CN
  share:
    enable: true
    Twitter: true
    Facebook: false
    Weibo: true

footer:
  enable: true
  since: 2023
  hugo: true
  siteTime:
    enable: true
    value: "2023-11-16T07:40:29+08:00"
  visitor:
    enable: false
  license: '<a rel="license external nofollow noopener noreferrer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'
  order:
    powered: 1
    copyright: last
    statistics: first

section:
  recentlyUpdated:
    enable: true

tagCloud:
  enable: true

# https://fixit.lruihao.cn/documentation/basics/#cdn-configuration
cdn:
  data: jsdelivr.yml

githubCorner:
  enable: true
  permalink: "https://github.com/will4j"
  title: "Visit Me on GitHub"
  position: left

# Busuanzi count
ibruce:
  enable: true
  enablePost: true

# 面包屑
breadcrumb:
  enable: true

app:
  svgFavicon: /favicon.svg

description: Programmer William Wang's blog.
keywords: ["Programming", "Software Engineering", "DevOps", "Kubernetes"]
